import TodoList from '@/app/todo/component/TodoList';

export const metadata = {
  title: 'Todo Page',
  description: 'Generated by create next app',
};

export default function TodoLayout({ children }: {
  children: React.ReactNode
}) {
  return (
    <div style={{display: 'flex'}}>
      <TodoList />
      <div>{children}</div>
    </div>
  );
}


